-- ============================================================
-- seed_golf_clubs.sql
-- 42 golf clubs (onetheclub deduplicated to 1 row)
-- Inactive clubs have scraper_type = 'playwright_inactive', is_active = false
-- ============================================================

INSERT INTO golf_clubs (
    id,
    name,
    url,
    origin,
    referer_login,
    referer_reservation,
    login_path,
    reservation_path,
    scraper_type,
    is_active
) VALUES

-- Active clubs --------------------------------------------------

('shinedale',
 '샤인데일',
 'https://www.shinedale.com',
 'https://www.shinedale.com',
 'https://www.shinedale.com',
 'https://www.shinedale.com/Reservation/Reservation.aspx',
 '/Member/Login.aspx',
 '/Reservation/Reservation.aspx',
 'requests', true),

('bearcreek',
 '베어크리크',
 'https://www.bearcreek.co.kr',
 'https://www.bearcreek.co.kr',
 'https://www.bearcreek.co.kr/Member/Login.aspx',
 'https://www.bearcreek.co.kr/Reservation/Reservation.aspx',
 '/Member/Login.aspx',
 '/Reservation/Reservation.aspx',
 'requests', true),

('taekwang',
 '태광CC',
 'https://www.taekwangcc.co.kr',
 'https://www.taekwangcc.co.kr',
 'https://www.taekwangcc.co.kr/Member/Login.aspx',
 'https://www.taekwangcc.co.kr/Reservation/Reservation.aspx',
 '/Member/Login.aspx',
 '/Reservation/Reservation.aspx',
 'requests', true),

('onetheclub',
 '원더클럽',
 'https://www.onetheclub.com',
 'https://www.onetheclub.com',
 'https://www.onetheclub.com/member/login',
 'https://www.onetheclub.com/reservation/golf',
 '/member/loginChk',
 '/reservation/ajax/golfTimeList',
 'requests', true),

('cc360',
 '360CC',
 'https://www.360cc.co.kr',
 'https://www.360cc.co.kr',
 'https://www.360cc.co.kr/user/sign/login.do',
 'https://www.360cc.co.kr/reservation/list.do',
 '/user/sign/setLoginCheck.do',
 '/reservation/list/ajax_real_timeinfo_list.do',
 'requests', true),

('purunsol',
 '푸른솔GC 포천',
 'https://www.purunsol.co.kr',
 'https://www.purunsol.co.kr',
 'https://www.purunsol.co.kr/Main/',
 'https://www.purunsol.co.kr/Booking/GolfCalendar.aspx',
 '/AJAX/member/services.asmx/Login',
 '/_AJAX/reservation/services.asmx/GetGolfTimeList',
 'requests', true),

('ga',
 'GA코리아',
 'https://www.gakorea.com',
 'https://www.gakorea.com',
 'https://www.gakorea.com/join/login.asp',
 'https://www.gakorea.com/Reservation/ReservationList.asp',
 '/join/login.asp',
 '/controller/ReservationController.asp',
 'requests', true),

('hilldeloci',
 '힐드로사이CC',
 'https://www.skyvalley.co.kr',
 'https://www.skyvalley.co.kr',
 'https://www.skyvalley.co.kr/hilldeloci/member/login',
 'https://www.skyvalley.co.kr/hilldeloci/reservation/golf',
 '/hilldeloci/member/loginChk',
 '/reservation/ajax/golfTimeList',
 'requests', true),

('skyvalley',
 '스카이밸리CC',
 'https://www.skyvalley.co.kr',
 'https://www.skyvalley.co.kr',
 'https://www.skyvalley.co.kr/skyvalley/member/login',
 'https://www.skyvalley.co.kr/skyvalley/reservation/golf',
 '/skyvalley/member/loginChk',
 '/reservation/ajax/golfTimeList',
 'requests', true),

('edenblue',
 '에덴블루CC',
 'https://www.edenblue.co.kr',
 'https://www.edenblue.co.kr',
 'https://www.edenblue.co.kr/login/login.asp',
 'https://www.edenblue.co.kr/GolfRes/onepage/real_timelist.asp',
 '/login/login_ok.asp',
 '/GolfRes/onepage/real_timelist_ajax_list.asp',
 'requests', true),

('lakewood',
 '레이크우드CC',
 'https://lakewood.co.kr',
 'https://lakewood.co.kr',
 'https://lakewood.co.kr/member/login',
 'https://lakewood.co.kr/reservation/golf',
 '/member/loginChk',
 '/reservation/ajax/golfTimeList',
 'requests', true),

('golfzoncounty',
 '골프존카운티',
 'https://www.golfzoncounty.com',
 'https://www.golfzoncounty.com',
 'https://www.golfzoncounty.com/member/login',
 'https://www.golfzoncounty.com/reserve/main',
 '/member/ajax/loginChk',
 '/reserve/ajax/bookgInfo',
 'requests', true),

('ferrum',
 '페럼클럽CC',
 'https://www.ferrumclub.com',
 'https://www.ferrumclub.com',
 'https://www.ferrumclub.com/lounge/login.asp',
 'https://www.ferrumclub.com/reservation/real_timelist.asp',
 '/lounge/login_ok.asp',
 '/reservation/real_timelist_ajax_list.asp',
 'requests', true),

('ehscc',
 '은화삼CC',
 'https://www.ehscc.co.kr',
 'https://www.ehscc.co.kr',
 'https://www.ehscc.co.kr/Member/Login',
 'https://www.ehscc.co.kr/Booking/GolfCalendar',
 '/Member/LoginAction',
 '/Ajax/Time',
 'requests', true),

('sunningpoint',
 '써닝포인트CC',
 'https://www.sunningpoint.com',
 'https://www.sunningpoint.com',
 'https://www.sunningpoint.com/login/login.asp',
 'https://www.sunningpoint.com/golfRes/real_timeList.asp',
 '/login/login_ok.asp',
 '/golfRes/real_timeList.asp',
 'requests', true),

('laviebell',
 '라비에벨CC',
 'https://lavieestbellegolfnresort.com/oldcourse',
 'https://lavieestbellegolfnresort.com',
 'https://lavieestbellegolfnresort.com/oldcourse/login/login.asp',
 'https://lavieestbellegolfnresort.com/oldcourse/GolfRes/onepage/real_timelist.asp',
 '/login/login_ok.asp',
 '/GolfRes/onepage/real_timelist_ajax_list.asp',
 'requests', true),

('yangju',
 '양주CC',
 'https://www.yangjucc.co.kr',
 'https://www.yangjucc.co.kr',
 'https://www.yangjucc.co.kr/login/login.asp',
 'https://www.yangjucc.co.kr/GolfRes/onepage/real_reservation.asp',
 '/login/login_ok.asp',
 '/GolfRes/onepage/real_timelist_ajax_list.asp',
 'requests', true),

('tpcgolf',
 '양평TPC',
 'http://www.tpcgolf.co.kr',
 'http://www.tpcgolf.co.kr',
 'http://www.tpcgolf.co.kr/Member/login_ok.asp',
 'http://www.tpcgolf.co.kr/Reservation/Reservation.asp',
 '/Member/login_ok.asp',
 '/Reservation/Inc/TimeTable_Amt.asp',
 'requests', true),

('midas',
 '마이다스',
 'https://www.midasgolf.co.kr',
 'https://www.midasgolf.co.kr',
 'http://www.tpcgolf.co.kr/Member/Login.html',
 'https://www.midasgolf.co.kr/Reservation',
 '/Member/Login',
 '/Reservation/AjaxTimeList',
 'requests', true),

('sonofelice',
 '소노펠리체',
 'https://www.sonofelicecc.com',
 'https://www.sonofelicecc.com',
 'https://www.sonofelicecc.com/login.dp/dmparse.dm',
 'https://www.sonofelicecc.com/reservation.dp/dmparse.dm',
 '/doLogin.dp/dmparse.dm',
 '/rsv.selectTimeScd.dp/dmparse.dm',
 'requests', true),

('oakvalley',
 '오크밸리',
 'https://reservation.oakvalley.co.kr',
 'https://reservation.oakvalley.co.kr',
 'https://reservation.oakvalley.co.kr/member/login.do',
 'https://reservation.oakvalley.co.kr/reservation/golf.do',
 '/frontMember.pns?login',
 '/golf.course.pns?getCourse_G',
 'requests', true),

('raycastle',
 '레이캐슬 골프&리조트',
 'https://www.sjraycastle.com',
 'https://www.sjraycastle.com',
 'https://www.sjraycastle.com/Golf/Booking/Login.aspx',
 'https://www.sjraycastle.com/Golf/Booking/Reservation.aspx',
 NULL,
 '/Golf/Booking/Reservation.aspx',
 'requests', true),

('seowon',
 '서원힐스CC',
 'https://www.seowongolf.co.kr',
 'https://www.seowongolf.co.kr',
 'https://www.seowongolf.co.kr/hills/member/login.do',
 'https://www.seowongolf.co.kr/hills/reservation',
 '/hills/member/actionLogin.do',
 '/hills/reservation/getTeeList.do',
 'requests', true),

('bearsbest',
 '베어즈베스트',
 'https://www.bearsbestcheongnagc.com',
 'https://www.bearsbestcheongnagc.com',
 'https://www.bearsbestcheongnagc.com/Member/Login',
 'https://www.bearsbestcheongnagc.com/Booking',
 '/Member/LoginAction',
 '/Booking/AjaxGetTime',
 'requests', true),

('thecrosby',
 '더크로스비GC',
 'https://www.thecrosbygc.co.kr',
 'https://www.thecrosbygc.co.kr',
 'https://www.thecrosbygc.co.kr/Member/Login.aspx',
 'https://www.thecrosbygc.co.kr/Reservation/Reservation.aspx',
 '/Member/Login.aspx',
 '/Reservation/Reservation.aspx',
 'requests', true),

('pinestone',
 '파인스톤CC',
 'https://www.pinestonecc.com',
 'https://www.pinestonecc.com',
 'https://www.pinestonecc.com/login/login.asp',
 'https://www.pinestonecc.com/GolfRes/onepage/real_timelist.asp',
 '/login/login_ok.asp',
 '/GolfRes/onepage/real_timelist_ajax_list.asp',
 'requests', true),

('theplayers',
 '더플레이어스',
 'https://www.clubd.com',
 'https://www.clubd.com',
 'https://www.clubd.com/clubd/member/login.do',
 'https://www.clubd.com/clubd/reservation',
 '/clubd/member/actionLogin.do',
 '/clubd/reservation/getTeeList.do',
 'requests', true),

('lassagc',
 '라싸GC',
 'https://www.lassagc.com',
 'https://www.lassagc.com',
 'https://www.lassagc.com/member/login',
 'https://www.lassagc.com/reservation',
 NULL,
 '/controller/ReservationController.asp',
 'requests', true),

('rainbowhills',
 '레인보우힐스CC',
 'https://www.rainbowhills.co.kr',
 'https://www.rainbowhills.co.kr',
 'https://www.rainbowhills.co.kr/login/login.asp',
 'https://www.rainbowhills.co.kr/index.asp',
 '/login/login_ok.asp',
 '/GolfRes/onepage/real_timelist_ajax_list.asp',
 'requests', true),

('orangedunesyj',
 '오렌지듄스영종GC',
 'https://api.orangedunesyj.com',
 'https://www.orangedunesyj.com',
 'https://www.orangedunesyj.com/',
 'https://www.orangedunesyj.com/',
 '/v1/auth/issue',
 '/v1/reservation-calender',
 'requests', true),

('samsunggolf',
 '삼성골프',
 'https://www.lakeside.kr',
 'https://www.lakeside.kr',
 'https://www.lakeside.kr/user/sign/login.do',
 'https://www.lakeside.kr/reservation/samsung_reservation.do',
 '/user/sign/setLoginCheck.do',
 '/reservation/list/ajax_real_timeinfo_list_golf_samsung.do',
 'requests', true),

('southspring',
 '사우스스프링스CC',
 'https://www.sscc.co.kr',
 'https://www.sscc.co.kr',
 'https://www.sscc.co.kr/login',
 'https://www.sscc.co.kr/02reservation/02reservation_time.asp',
 '/hp/api/member/login',
 '/hp/api/reservation/sheets/non-member/KBLFG/',
 'requests', true),

('philosgc',
 '필로스CC',
 'https://www.philosgc.com',
 'https://www.philosgc.com',
 'https://www.philosgc.com/login/login.asp',
 'https://www.philosgc.com/reservation/reservation.aspx',
 '/login/login.asp',
 '/Reservation/Reservation.aspx?SelectedDate=',
 'requests', true),

('jungbu',
 '중부CC',
 'https://www.akdjbcc.co.kr',
 'https://www.akdjbcc.co.kr',
 NULL,
 NULL,
 '/html/member/login_ok.asp',
 NULL,
 'requests', true),

('cascadia',
 '카스카디아CC',
 'https://cascadia.kr',
 'https://cascadia.kr',
 'https://cascadia.kr/member/login',
 'https://cascadia.kr/reservation/golf',
 '/member/loginChk',
 '/reservation/ajax/golfTimeList',
 'requests', true),

('sungmoon',
 '성문안CC',
 'https://reservation.oakvalley.co.kr',
 'https://reservation.oakvalley.co.kr',
 'https://reservation.oakvalley.co.kr/frontMember.pns?loginForm',
 'https://reservation.oakvalley.co.kr/golf.course.pns?courseMain',
 '/frontMember.pns?login',
 '/golf.course.pns?getCourse_G',
 'requests', true),

-- Inactive clubs (playwright_inactive) -------------------------

('namchuncheon_new',
 '남춘천CC',
 'https://www.namchuncheon.co.kr',
 'https://www.namchuncheon.co.kr',
 'https://www.namchuncheon.co.kr',
 'https://www.namchuncheon.co.kr',
 '/member/login',
 '/booking/real-time',
 'playwright_inactive', false),

('owners_new',
 '오너스GC',
 'https://www.ownersgc.co.kr',
 'https://www.ownersgc.co.kr',
 'https://www.ownersgc.co.kr/html/member/login.asp',
 'https://www.ownersgc.co.kr/html/reservation/reservation_01_01.asp',
 '/html/member/login.asp',
 '/html/reservation/reservation_01_01.asp',
 'playwright_inactive', false),

('lakeside_new',
 '레이크사이드CC',
 'https://www.lakeside.kr',
 'https://www.lakeside.kr',
 'https://www.lakeside.kr/login/login.do',
 'https://www.lakeside.kr/reservation/real_reservation.do',
 '/login/login.do',
 '/reservation/real_reservation.do',
 'playwright_inactive', false),

('fortunehills',
 '포천힐스CC',
 'https://www.fortunehills.co.kr',
 'https://www.fortunehills.co.kr',
 'https://www.fortunehills.co.kr/Member/Login.aspx',
 'https://www.fortunehills.co.kr/Reservation/Reservation.aspx',
 NULL,
 '/Reservation/Reservation.aspx',
 'playwright_inactive', false),

('namyeoju',
 '남여주CC',
 'https://www.namyeoju.co.kr',
 'https://www.namyeoju.co.kr',
 'https://www.namyeoju.co.kr/login/login.asp',
 'https://www.namyeoju.co.kr/reservation/golf',
 '/login/login.asp',
 '/Reservation/Reservation.aspx',
 'playwright_inactive', false)

ON CONFLICT (id) DO NOTHING;
